add check tests results

diff --git a/.github/workflows/check_build_test_and_push_template.yml b/.github/workflows/check_build_test_and_push_template.yml
--- a/.github/workflows/check_build_test_and_push_template.yml
+++ b/.github/workflows/check_build_test_and_push_template.yml
@@ -38,20 +38,9 @@ jobs:
       - name: Create network
         run: docker network create docker_network
       - name: Run rfswarm agent
-        id: agent_run
         run: |
           docker run --rm -d --name agent --hostname agent --network docker_network \
           rfswarm-image-for-check
-          echo "exit_code=$?" >> $GITHUB_OUTPUT
-      - name: Check test result
-        run: |
-          echo "Robot Framework test running on agent exit code: ${{ steps.agent_run.outputs.exit_code }}"
-          if [ "${{ steps.agent_run.outputs.exit_code }}" -ne 0 ]; then
-            echo  "Test fail"
-            exit 1
-          else
-            echo "Test success"
-          fi    
       - name: Run ssh sever
         if: ${{ contains(inputs.IMAGE, 'agent/sshlibrary') }}
         run: |
@@ -71,6 +60,16 @@ jobs:
             -v $(pwd)/tests/suites:/src/tests -v ${{ github.workspace }}/reports:/src/reports \
             rfswarm-docker-manager
           fi
+      - name: Check test result
+        if: "${{ github.workspace }}/report/output.xml"
+        run: |
+          ${exit_code} =  rebot ${{ github.workspace }}/report/output.xml
+          if [ ${exit_code} -ne 0 ]; then
+            echo  "Test fail"
+            exit 1
+          else
+            echo "Test success"
+          fi        
       - name: Prepare artifact name
         id: prep
         run: echo "image_name_safe=$(echo "${{ inputs.IMAGE }}" | tr '/' '_')" >> $GITHUB_OUTPUT
